Added ability for additional, custom fingerprints.
projectdiscovery/wappalyzergo pull request #109
Opened 2024-11-07 16:55 UTC by SecGus

As title, added the ability to specify a custom fingerprints file as an argument (optional). This will append the custom fingerprints to the main, original list of fingerprints.

2024-11-08 11:12 UTC, GeorginaReeder commented
Thanks so much for your contribution @SecGus ! :)

We also have a [Discord server](https://discord.com/invite/projectdiscovery), which you’re more than welcome to join. It's a great place to connect with fellow contributors and stay updated with the latest developments!

2024-11-20 08:29 UTC, dogancanbakir requested changes

2024-11-20 08:29 UTC, dogancanbakir commented on tech.go
> +func New(customFilePaths ...string) (*Wappalyze, error) {
How about we rename the `loadFingerprints` as `loadDefaultFingerprints` and then introduce a new method called something like `AddFingerprints` etc., to make it cleaner?

2025-05-11 15:38 UTC, dogancanbakir commented
Closing this due to prolonged inactivity and also there is new PR close to this one https://github.com/projectdiscovery/wappalyzergo/pull/122.

2025-05-11 15:38 UTC, closed without merging